global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'java-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'mongodb'
    static_configs:
      - targets: [ 'host.docker.internal:9216' ]

  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: 'node'
    static_configs:
      - targets: [ 'node_exporter:9100' ]